### ISSUE TITLE
`feature_importances` doesn't work in iterated model

### ISSUE THREAD

**Issue by Moelf** [JuliaAI/MLJIteration.jl#66]
![image](https://github.com/user-attachments/assets/9a165d38-1563-454f-bde3-f8a2e45fc6ec)
![image](https://github.com/user-attachments/assets/79bdd06c-305b-4e04-8e45-9a82559ec9ca)
![image](https://github.com/user-attachments/assets/b782e188-8300-41c1-8596-5931839a769c)

**Comment by ablaom** [comment]
I think the same forwarding we have for the [TunedModel](https://github.com/JuliaAI/MLJTuning.jl/blob/cca89bd4288aa200841e6106b3c263036504f26e/src/tuned_models.jl#L904) wrapper works here.

**Comment by ablaom** [comment]
@Moelf As a workaround, can you try `feature_importances(fitted_params(mach_bdt).machine)`, assuming `mach_bdt` is the machine bound to your `IteratedModel` instance.
